import { ProductType } from "@/backend";
import type { DesignTemplate } from "@/types";

/** Gallery filter chips (the "All" chip is added by the page). */
export const TEMPLATE_CATEGORIES = [
  "Postcards",
  "Letters & Envelopes",
  "Flyers & Brochures",
  "Secure Mailers",
  "Booklets",
] as const;

export type TemplateCategory = (typeof TEMPLATE_CATEGORIES)[number];

/** Print-ready starting points, sized for the catalog formats they target. */
export const TEMPLATES: DesignTemplate[] = [
  {
    id: "pc-001",
    name: "Real Estate Just Listed 4×6",
    category: "Postcards",
    industry: "Real Estate",
    productType: ProductType.Postcard,
    layoutVariant: "4.25x6",
    thumbnailDescription:
      "Dark navy real estate card with address text and For Sale badge",
    backgroundColor: "#0f1a2e",
    textBlocks: [
      { text: "JUST LISTED", x: 8, y: 12, fontSize: 18, color: "#ffffff" },
      { text: "123 Main Street", x: 8, y: 34, fontSize: 14, color: "#cbd5e1" },
    ],
    hasQrCode: false,
    sizeLabel: "6″ × 4.25″ postcard",
    gradient: "linear-gradient(135deg, #0f1a2e 0%, #1e3a5f 50%, #0f1a2e 100%)",
    accentColor: "#f59e0b",
    overlayText: "FOR SALE",
  },
  {
    id: "pc-002",
    name: "Cart Abandonment Retargeting 4×6",
    category: "Postcards",
    industry: "E-Commerce",
    productType: ProductType.Postcard,
    layoutVariant: "4.25x6",
    thumbnailDescription:
      "Warm gradient with We miss you copy for e-commerce retargeting",
    backgroundColor: "#2d1b14",
    textBlocks: [
      { text: "We miss you!", x: 8, y: 12, fontSize: 18, color: "#ffffff" },
      {
        text: "Come back and save 15%",
        x: 8,
        y: 34,
        fontSize: 12,
        color: "#fed7aa",
      },
    ],
    hasQrCode: true,
    sizeLabel: "6″ × 4.25″ postcard",
    gradient: "linear-gradient(135deg, #2d1b14 0%, #7c2d12 50%, #ea580c 100%)",
    accentColor: "#f97316",
    overlayText: "15% OFF",
  },
  {
    id: "pc-003",
    name: "Restaurant Grand Opening 6×9",
    category: "Postcards",
    industry: "Retail + Restaurants",
    productType: ProductType.Postcard,
    layoutVariant: "6x9",
    thumbnailDescription:
      "Bold red and gold restaurant grand opening announcement",
    backgroundColor: "#450a0a",
    textBlocks: [
      { text: "GRAND OPENING", x: 8, y: 12, fontSize: 20, color: "#fef08a" },
      {
        text: "Free appetizer with entrée",
        x: 8,
        y: 36,
        fontSize: 12,
        color: "#fca5a5",
      },
    ],
    hasQrCode: false,
    sizeLabel: "9″ × 6″ postcard",
    gradient: "linear-gradient(135deg, #450a0a 0%, #991b1b 50%, #b45309 100%)",
    accentColor: "#facc15",
    overlayText: "NOW OPEN",
  },
  {
    id: "pc-004",
    name: "Jumbo Spotlight Farm Mailer 6×11",
    category: "Postcards",
    industry: "Real Estate",
    productType: ProductType.Postcard,
    layoutVariant: "6x11",
    thumbnailDescription: "Real estate aerial photo style jumbo farm mailer",
    backgroundColor: "#0c1929",
    textBlocks: [
      { text: "FARM MAILER", x: 8, y: 12, fontSize: 18, color: "#ffffff" },
      {
        text: "Your neighborhood specialist",
        x: 8,
        y: 34,
        fontSize: 12,
        color: "#94a3b8",
      },
    ],
    hasQrCode: true,
    sizeLabel: "11″ × 6″ postcard",
    gradient: "linear-gradient(135deg, #0c1929 0%, #1e40af 40%, #0f172a 100%)",
    accentColor: "#3b82f6",
    overlayText: "JUMBO",
  },
  {
    id: "pc-005",
    name: "Healthcare Appointment Reminder 6×9",
    category: "Postcards",
    industry: "Healthcare",
    productType: ProductType.Postcard,
    layoutVariant: "6x9",
    thumbnailDescription: "Clean clinical white and blue appointment reminder",
    backgroundColor: "#f0f9ff",
    textBlocks: [
      {
        text: "APPOINTMENT REMINDER",
        x: 8,
        y: 12,
        fontSize: 16,
        color: "#0369a1",
      },
      {
        text: "Your health matters to us",
        x: 8,
        y: 34,
        fontSize: 12,
        color: "#0ea5e9",
      },
    ],
    hasQrCode: false,
    sizeLabel: "9″ × 6″ postcard",
    gradient: "linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 50%, #bae6fd 100%)",
    accentColor: "#0284c7",
    overlayText: "HEALTH",
  },
  {
    id: "lt-001",
    name: "Professional B2B Invoice Letter",
    category: "Letters & Envelopes",
    industry: "All",
    productType: ProductType.Letter,
    layoutVariant: "letter",
    thumbnailDescription: "Clean corporate letterhead with invoice styling",
    backgroundColor: "#ffffff",
    textBlocks: [
      { text: "INVOICE", x: 10, y: 8, fontSize: 22, color: "#1e293b" },
      {
        text: "Invoice #2026-001",
        x: 10,
        y: 18,
        fontSize: 12,
        color: "#64748b",
      },
    ],
    hasQrCode: false,
    sizeLabel: "8.5″ × 11″",
    gradient: "linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)",
    accentColor: "#334155",
    overlayText: "B2B",
  },
  {
    id: "lt-002",
    name: "Legal Notice Formal Letter",
    category: "Letters & Envelopes",
    industry: "All",
    productType: ProductType.Letter,
    layoutVariant: "letter",
    thumbnailDescription: "Formal serif style legal notice letterhead",
    backgroundColor: "#fafaf9",
    textBlocks: [
      { text: "LEGAL NOTICE", x: 10, y: 8, fontSize: 20, color: "#292524" },
      {
        text: "Please review the enclosed documents",
        x: 10,
        y: 18,
        fontSize: 11,
        color: "#78716c",
      },
    ],
    hasQrCode: false,
    sizeLabel: "8.5″ × 11″",
    gradient: "linear-gradient(180deg, #fafaf9 0%, #e7e5e4 100%)",
    accentColor: "#44403c",
    overlayText: "LEGAL",
  },
  {
    id: "lt-003",
    name: "Customer Welcome Package Letter",
    category: "Letters & Envelopes",
    industry: "E-Commerce",
    productType: ProductType.Letter,
    layoutVariant: "letter",
    thumbnailDescription: "Branded warm introduction welcome letter",
    backgroundColor: "#fffbeb",
    textBlocks: [
      { text: "WELCOME", x: 10, y: 8, fontSize: 24, color: "#92400e" },
      {
        text: "Thank you for choosing us",
        x: 10,
        y: 19,
        fontSize: 12,
        color: "#b45309",
      },
    ],
    hasQrCode: true,
    sizeLabel: "8.5″ × 11″",
    gradient: "linear-gradient(180deg, #fffbeb 0%, #fef3c7 100%)",
    accentColor: "#d97706",
    overlayText: "WELCOME",
  },
  {
    id: "sm-001",
    name: "Restaurant Bifold Menu Mailer",
    category: "Flyers & Brochures",
    industry: "Retail + Restaurants",
    productType: ProductType.Flyer,
    layoutVariant: "8.5x11_flyer",
    thumbnailDescription: "Food photography style bifold menu panels",
    backgroundColor: "#1a0f0a",
    textBlocks: [
      { text: "MENU", x: 6, y: 12, fontSize: 22, color: "#fef3c7" },
      {
        text: "Seasonal specials inside",
        x: 6,
        y: 40,
        fontSize: 11,
        color: "#d6d3d1",
      },
    ],
    hasQrCode: false,
    sizeLabel: "8.5″ × 11″ flyer · bifold",
    gradient: "linear-gradient(135deg, #1a0f0a 0%, #451a03 50%, #78350f 100%)",
    accentColor: "#fbbf24",
    overlayText: "MENU",
  },
  {
    id: "sm-002",
    name: "Trifold Product Catalog",
    category: "Flyers & Brochures",
    industry: "E-Commerce",
    productType: ProductType.Brochure,
    layoutVariant: "11x8.5_brochure",
    thumbnailDescription: "E-commerce product grid trifold catalog",
    backgroundColor: "#0f172a",
    textBlocks: [
      { text: "SPRING CATALOG", x: 6, y: 10, fontSize: 18, color: "#e2e8f0" },
      {
        text: "New arrivals & bestsellers",
        x: 6,
        y: 24,
        fontSize: 11,
        color: "#94a3b8",
      },
    ],
    hasQrCode: true,
    sizeLabel: "11″ × 8.5″ brochure · trifold",
    gradient: "linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #334155 100%)",
    accentColor: "#818cf8",
    overlayText: "CATALOG",
  },
  {
    id: "sm-003",
    name: "Healthcare Services Brochure",
    category: "Flyers & Brochures",
    industry: "Healthcare",
    productType: ProductType.Flyer,
    layoutVariant: "8.5x11_flyer",
    thumbnailDescription: "Clean medical panels bifold brochure",
    backgroundColor: "#ecfeff",
    textBlocks: [
      { text: "OUR SERVICES", x: 6, y: 12, fontSize: 18, color: "#155e75" },
      {
        text: "Comprehensive care for your family",
        x: 6,
        y: 40,
        fontSize: 11,
        color: "#0891b2",
      },
    ],
    hasQrCode: false,
    sizeLabel: "8.5″ × 11″ flyer · bifold",
    gradient: "linear-gradient(135deg, #ecfeff 0%, #cffafe 50%, #a5f3fc 100%)",
    accentColor: "#06b6d4",
    overlayText: "CARE",
  },
  {
    id: "sp-001",
    name: "Security Notice Secure Mailer",
    category: "Secure Mailers",
    industry: "All",
    productType: ProductType.SnapPack,
    layoutVariant: "8.5x11_secure",
    thumbnailDescription:
      "Official warning header with perforated edges visual",
    backgroundColor: "#fefce8",
    textBlocks: [
      {
        text: "IMPORTANT NOTICE",
        x: 10,
        y: 8,
        fontSize: 18,
        color: "#854d0e",
      },
      {
        text: "Please open immediately",
        x: 10,
        y: 18,
        fontSize: 11,
        color: "#a16207",
      },
    ],
    hasQrCode: false,
    sizeLabel: "8.5″ × 11″",
    gradient: "linear-gradient(180deg, #fefce8 0%, #fef9c3 100%)",
    accentColor: "#ca8a04",
    overlayText: "URGENT",
  },
  {
    id: "sp-002",
    name: "Physical Check Mailer",
    category: "Secure Mailers",
    industry: "All",
    productType: ProductType.SnapPack,
    layoutVariant: "8.5x11_secure",
    thumbnailDescription: "Check stub style layout with perforated edges",
    backgroundColor: "#f0fdf4",
    textBlocks: [
      {
        text: "PAYMENT ENCLOSED",
        x: 10,
        y: 8,
        fontSize: 18,
        color: "#166534",
      },
      {
        text: "Do not bend — check inside",
        x: 10,
        y: 18,
        fontSize: 11,
        color: "#15803d",
      },
    ],
    hasQrCode: false,
    sizeLabel: "8.5″ × 11″",
    gradient: "linear-gradient(180deg, #f0fdf4 0%, #dcfce7 100%)",
    accentColor: "#16a34a",
    overlayText: "CHECK",
  },
  {
    id: "sp-003",
    name: "Insurance Policy Notice",
    category: "Secure Mailers",
    industry: "Healthcare",
    productType: ProductType.SnapPack,
    layoutVariant: "8.5x11_secure",
    thumbnailDescription: "Formal policy document style with security header",
    backgroundColor: "#eff6ff",
    textBlocks: [
      { text: "POLICY UPDATE", x: 10, y: 8, fontSize: 18, color: "#1e40af" },
      {
        text: "Review changes to your coverage",
        x: 10,
        y: 18,
        fontSize: 11,
        color: "#3b82f6",
      },
    ],
    hasQrCode: false,
    sizeLabel: "8.5″ × 11″",
    gradient: "linear-gradient(180deg, #eff6ff 0%, #dbeafe 100%)",
    accentColor: "#2563eb",
    overlayText: "POLICY",
  },
  {
    id: "bk-001",
    name: "Multi-Product Retail Catalog",
    category: "Booklets",
    industry: "Retail + Restaurants",
    productType: ProductType.Booklet,
    layoutVariant: "8.5x11_booklet",
    thumbnailDescription: "Colorful product grid multi-page catalog",
    backgroundColor: "#fdf4ff",
    textBlocks: [
      { text: "2026 CATALOG", x: 10, y: 8, fontSize: 18, color: "#86198f" },
      {
        text: "Everything you need in one place",
        x: 10,
        y: 18,
        fontSize: 11,
        color: "#a21caf",
      },
    ],
    hasQrCode: true,
    sizeLabel: "8.5″ × 11″ booklet self mailer",
    gradient: "linear-gradient(135deg, #fdf4ff 0%, #fae8ff 50%, #f5d0fe 100%)",
    accentColor: "#c026d3",
    overlayText: "CATALOG",
  },
  {
    id: "bk-002",
    name: "Annual Report Booklet",
    category: "Booklets",
    industry: "All",
    productType: ProductType.Booklet,
    layoutVariant: "8.5x11_booklet",
    thumbnailDescription: "Corporate executive style annual report",
    backgroundColor: "#f8fafc",
    textBlocks: [
      { text: "ANNUAL REPORT", x: 10, y: 8, fontSize: 18, color: "#334155" },
      {
        text: "Fiscal year 2026 highlights",
        x: 10,
        y: 18,
        fontSize: 11,
        color: "#64748b",
      },
    ],
    hasQrCode: false,
    sizeLabel: "8.5″ × 11″ booklet self mailer",
    gradient: "linear-gradient(135deg, #f8fafc 0%, #e2e8f0 50%, #cbd5e1 100%)",
    accentColor: "#475569",
    overlayText: "REPORT",
  },
  {
    id: "bk-003",
    name: "Healthcare Service Directory",
    category: "Booklets",
    industry: "Healthcare",
    productType: ProductType.Booklet,
    layoutVariant: "8.5x11_booklet",
    thumbnailDescription: "Medical directory pages with service listings",
    backgroundColor: "#ecfeff",
    textBlocks: [
      {
        text: "SERVICE DIRECTORY",
        x: 10,
        y: 8,
        fontSize: 16,
        color: "#155e75",
      },
      {
        text: "Find the right care for you",
        x: 10,
        y: 18,
        fontSize: 11,
        color: "#0e7490",
      },
    ],
    hasQrCode: false,
    sizeLabel: "8.5″ × 11″ booklet self mailer",
    gradient: "linear-gradient(135deg, #ecfeff 0%, #cffafe 50%, #a5f3fc 100%)",
    accentColor: "#0891b2",
    overlayText: "DIRECTORY",
  },
];

/** Templates that fit a layout variant, then the rest of its product family. */
export function templatesForLayout(
  layoutVariant: string,
  productType: ProductType | null,
): DesignTemplate[] {
  const exact = TEMPLATES.filter((t) => t.layoutVariant === layoutVariant);
  const family = productType
    ? TEMPLATES.filter(
        (t) =>
          t.productType === productType && t.layoutVariant !== layoutVariant,
      )
    : [];
  return [...exact, ...family];
}
