/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductType = IDL.Variant({
  'SelfMailer' : IDL.Null,
  'Booklet' : IDL.Null,
  'Letter' : IDL.Null,
  'SnapPack' : IDL.Null,
  'Postcard' : IDL.Null,
});
export const ProductSelection = IDL.Record({
  'productType' : ProductType,
  'layoutVariant' : IDL.Text,
  'colorOption' : IDL.Opt(IDL.Text),
});
export const AudienceType = IDL.Variant({ 'CSV' : IDL.Null, 'Map' : IDL.Null });
export const AdminKeys = IDL.Record({
  'resendKey' : IDL.Opt(IDL.Text),
  'lobKey' : IDL.Opt(IDL.Text),
  'stripeKey' : IDL.Opt(IDL.Text),
});
export const CampaignStatus = IDL.Variant({
  'InTransit' : IDL.Null,
  'InProduction' : IDL.Null,
  'Delivered' : IDL.Null,
  'Created' : IDL.Null,
  'SortedAtLocalHub' : IDL.Null,
});
export const LogoState = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'id' : IDL.Text,
  'url' : IDL.Text,
  'height' : IDL.Float64,
  'width' : IDL.Float64,
});
export const TextBlockState = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'id' : IDL.Text,
  'height' : IDL.Float64,
  'color' : IDL.Text,
  'text' : IDL.Text,
  'width' : IDL.Float64,
  'fontSize' : IDL.Float64,
});
export const QrCodeState = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'id' : IDL.Text,
  'url' : IDL.Text,
  'size' : IDL.Float64,
});
export const CanvasState = IDL.Record({
  'backgroundImageUrl' : IDL.Opt(IDL.Text),
  'logos' : IDL.Vec(LogoState),
  'textBlocks' : IDL.Vec(TextBlockState),
  'qrCode' : IDL.Opt(QrCodeState),
});
export const CampaignRecordShared = IDL.Record({
  'id' : IDL.Text,
  'status' : CampaignStatus,
  'createdAt' : IDL.Int,
  'trackingId' : IDL.Opt(IDL.Text),
  'canvasState' : IDL.Opt(CanvasState),
  'designTemplateId' : IDL.Opt(IDL.Text),
  'recipientCount' : IDL.Nat,
  'audienceType' : AudienceType,
  'product' : ProductSelection,
});
export const TrackingEvent = IDL.Record({
  'lobEventId' : IDL.Text,
  'campaignId' : IDL.Text,
  'timestamp' : IDL.Int,
  'eventType' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const AddressInput = IDL.Record({
  'zip_code' : IDL.Text,
  'address_line1' : IDL.Text,
  'address_line2' : IDL.Opt(IDL.Text),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
});
export const VerifiedAddress = IDL.Record({
  'zip_code' : IDL.Text,
  'address_line1' : IDL.Text,
  'address_line2' : IDL.Opt(IDL.Text),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'zip_plus4' : IDL.Opt(IDL.Text),
});
export const AddressVerificationResult = IDL.Record({
  'verified' : IDL.Opt(VerifiedAddress),
  'errorMessage' : IDL.Opt(IDL.Text),
  'input' : AddressInput,
  'isValid' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createCampaign' : IDL.Func(
      [ProductSelection, IDL.Nat, AudienceType],
      [IDL.Text],
      [],
    ),
  'exportCampaignRecipients' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'fireLobOutcall' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'getAdminKeys' : IDL.Func([], [AdminKeys], []),
  'getCampaign' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CampaignRecordShared)],
      ['query'],
    ),
  'getCampaigns' : IDL.Func([], [IDL.Vec(CampaignRecordShared)], ['query']),
  'getCanvasState' : IDL.Func([IDL.Text], [IDL.Opt(CanvasState)], ['query']),
  'getTrackingEvents' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TrackingEvent)],
      ['query'],
    ),
  'handleLobWebhook' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveAdminKeys' : IDL.Func([AdminKeys], [IDL.Bool], []),
  'saveCanvasState' : IDL.Func([IDL.Text, CanvasState], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCampaignStatus' : IDL.Func(
      [IDL.Text, CampaignStatus, IDL.Text, IDL.Int],
      [IDL.Bool],
      [],
    ),
  'verifyAddresses' : IDL.Func(
      [IDL.Vec(AddressInput)],
      [IDL.Vec(AddressVerificationResult)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductType = IDL.Variant({
    'SelfMailer' : IDL.Null,
    'Booklet' : IDL.Null,
    'Letter' : IDL.Null,
    'SnapPack' : IDL.Null,
    'Postcard' : IDL.Null,
  });
  const ProductSelection = IDL.Record({
    'productType' : ProductType,
    'layoutVariant' : IDL.Text,
    'colorOption' : IDL.Opt(IDL.Text),
  });
  const AudienceType = IDL.Variant({ 'CSV' : IDL.Null, 'Map' : IDL.Null });
  const AdminKeys = IDL.Record({
    'resendKey' : IDL.Opt(IDL.Text),
    'lobKey' : IDL.Opt(IDL.Text),
    'stripeKey' : IDL.Opt(IDL.Text),
  });
  const CampaignStatus = IDL.Variant({
    'InTransit' : IDL.Null,
    'InProduction' : IDL.Null,
    'Delivered' : IDL.Null,
    'Created' : IDL.Null,
    'SortedAtLocalHub' : IDL.Null,
  });
  const LogoState = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'id' : IDL.Text,
    'url' : IDL.Text,
    'height' : IDL.Float64,
    'width' : IDL.Float64,
  });
  const TextBlockState = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'id' : IDL.Text,
    'height' : IDL.Float64,
    'color' : IDL.Text,
    'text' : IDL.Text,
    'width' : IDL.Float64,
    'fontSize' : IDL.Float64,
  });
  const QrCodeState = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'id' : IDL.Text,
    'url' : IDL.Text,
    'size' : IDL.Float64,
  });
  const CanvasState = IDL.Record({
    'backgroundImageUrl' : IDL.Opt(IDL.Text),
    'logos' : IDL.Vec(LogoState),
    'textBlocks' : IDL.Vec(TextBlockState),
    'qrCode' : IDL.Opt(QrCodeState),
  });
  const CampaignRecordShared = IDL.Record({
    'id' : IDL.Text,
    'status' : CampaignStatus,
    'createdAt' : IDL.Int,
    'trackingId' : IDL.Opt(IDL.Text),
    'canvasState' : IDL.Opt(CanvasState),
    'designTemplateId' : IDL.Opt(IDL.Text),
    'recipientCount' : IDL.Nat,
    'audienceType' : AudienceType,
    'product' : ProductSelection,
  });
  const TrackingEvent = IDL.Record({
    'lobEventId' : IDL.Text,
    'campaignId' : IDL.Text,
    'timestamp' : IDL.Int,
    'eventType' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const AddressInput = IDL.Record({
    'zip_code' : IDL.Text,
    'address_line1' : IDL.Text,
    'address_line2' : IDL.Opt(IDL.Text),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
  });
  const VerifiedAddress = IDL.Record({
    'zip_code' : IDL.Text,
    'address_line1' : IDL.Text,
    'address_line2' : IDL.Opt(IDL.Text),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'zip_plus4' : IDL.Opt(IDL.Text),
  });
  const AddressVerificationResult = IDL.Record({
    'verified' : IDL.Opt(VerifiedAddress),
    'errorMessage' : IDL.Opt(IDL.Text),
    'input' : AddressInput,
    'isValid' : IDL.Bool,
  });
  
  return IDL.Service({
    'createCampaign' : IDL.Func(
        [ProductSelection, IDL.Nat, AudienceType],
        [IDL.Text],
        [],
      ),
    'exportCampaignRecipients' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'fireLobOutcall' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'getAdminKeys' : IDL.Func([], [AdminKeys], []),
    'getCampaign' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CampaignRecordShared)],
        ['query'],
      ),
    'getCampaigns' : IDL.Func([], [IDL.Vec(CampaignRecordShared)], ['query']),
    'getCanvasState' : IDL.Func([IDL.Text], [IDL.Opt(CanvasState)], ['query']),
    'getTrackingEvents' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TrackingEvent)],
        ['query'],
      ),
    'handleLobWebhook' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveAdminKeys' : IDL.Func([AdminKeys], [IDL.Bool], []),
    'saveCanvasState' : IDL.Func([IDL.Text, CanvasState], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCampaignStatus' : IDL.Func(
        [IDL.Text, CampaignStatus, IDL.Text, IDL.Int],
        [IDL.Bool],
        [],
      ),
    'verifyAddresses' : IDL.Func(
        [IDL.Vec(AddressInput)],
        [IDL.Vec(AddressVerificationResult)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };