/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddressInput {
  'zip_code' : string,
  'address_line1' : string,
  'address_line2' : [] | [string],
  'city' : string,
  'name' : string,
  'state' : string,
}
export interface AddressVerificationResult {
  'verified' : [] | [VerifiedAddress],
  'errorMessage' : [] | [string],
  'input' : AddressInput,
  'isValid' : boolean,
}
export interface AdminKeys {
  'resendKey' : [] | [string],
  'lobKey' : [] | [string],
  'stripeKey' : [] | [string],
}
export type AudienceType = { 'CSV' : null } |
  { 'Map' : null };
export interface CampaignRecordShared {
  'id' : string,
  'status' : CampaignStatus,
  'createdAt' : bigint,
  'trackingId' : [] | [string],
  'canvasState' : [] | [CanvasState],
  'designTemplateId' : [] | [string],
  'recipientCount' : bigint,
  'audienceType' : AudienceType,
  'product' : ProductSelection,
}
export type CampaignStatus = { 'InTransit' : null } |
  { 'InProduction' : null } |
  { 'Delivered' : null } |
  { 'Created' : null } |
  { 'SortedAtLocalHub' : null };
export interface CanvasState {
  'backgroundImageUrl' : [] | [string],
  'logos' : Array<LogoState>,
  'textBlocks' : Array<TextBlockState>,
  'qrCode' : [] | [QrCodeState],
}
export interface LogoState {
  'x' : number,
  'y' : number,
  'id' : string,
  'url' : string,
  'height' : number,
  'width' : number,
}
export interface ProductSelection {
  'productType' : ProductType,
  'layoutVariant' : string,
  'colorOption' : [] | [string],
}
export type ProductType = { 'SelfMailer' : null } |
  { 'Booklet' : null } |
  { 'Letter' : null } |
  { 'SnapPack' : null } |
  { 'Postcard' : null };
export interface QrCodeState {
  'x' : number,
  'y' : number,
  'id' : string,
  'url' : string,
  'size' : number,
}
export interface TextBlockState {
  'x' : number,
  'y' : number,
  'id' : string,
  'height' : number,
  'color' : string,
  'text' : string,
  'width' : number,
  'fontSize' : number,
}
export interface TrackingEvent {
  'lobEventId' : string,
  'campaignId' : string,
  'timestamp' : bigint,
  'eventType' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface VerifiedAddress {
  'zip_code' : string,
  'address_line1' : string,
  'address_line2' : [] | [string],
  'city' : string,
  'name' : string,
  'state' : string,
  'zip_plus4' : [] | [string],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createCampaign' : ActorMethod<
    [ProductSelection, bigint, AudienceType],
    string
  >,
  'exportCampaignRecipients' : ActorMethod<[string], [] | [string]>,
  'fireLobOutcall' : ActorMethod<[string, string, string], string>,
  'getAdminKeys' : ActorMethod<[], AdminKeys>,
  'getCampaign' : ActorMethod<[string], [] | [CampaignRecordShared]>,
  'getCampaigns' : ActorMethod<[], Array<CampaignRecordShared>>,
  'getCanvasState' : ActorMethod<[string], [] | [CanvasState]>,
  'getTrackingEvents' : ActorMethod<[string], Array<TrackingEvent>>,
  'handleLobWebhook' : ActorMethod<[string], boolean>,
  'saveAdminKeys' : ActorMethod<[AdminKeys], boolean>,
  'saveCanvasState' : ActorMethod<[string, CanvasState], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCampaignStatus' : ActorMethod<
    [string, CampaignStatus, string, bigint],
    boolean
  >,
  'verifyAddresses' : ActorMethod<
    [Array<AddressInput>],
    Array<AddressVerificationResult>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];