/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QrCodeState {
    x: number;
    y: number;
    id: string;
    url: string;
    size: number;
}
export interface TextBlockState {
    x: number;
    y: number;
    id: string;
    height: number;
    color: string;
    text: string;
    width: number;
    fontSize: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TrackingEvent {
    lobEventId: string;
    campaignId: string;
    timestamp: bigint;
    eventType: string;
}
export interface ProductSelection {
    productType: ProductType;
    layoutVariant: string;
    colorOption?: string;
}
export interface AddressInput {
    zip_code: string;
    address_line1: string;
    address_line2?: string;
    city: string;
    name: string;
    state: string;
}
export interface LogoState {
    x: number;
    y: number;
    id: string;
    url: string;
    height: number;
    width: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CanvasState {
    backgroundImageUrl?: string;
    logos: Array<LogoState>;
    textBlocks: Array<TextBlockState>;
    qrCode?: QrCodeState;
}
export interface CampaignRecordShared {
    id: string;
    status: CampaignStatus;
    createdAt: bigint;
    trackingId?: string;
    canvasState?: CanvasState;
    designTemplateId?: string;
    recipientCount: bigint;
    audienceType: AudienceType;
    product: ProductSelection;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AdminKeys {
    resendKey?: string;
    lobKey?: string;
    stripeKey?: string;
}
export interface AddressVerificationResult {
    verified?: VerifiedAddress;
    errorMessage?: string;
    input: AddressInput;
    isValid: boolean;
}
export interface VerifiedAddress {
    zip_code: string;
    address_line1: string;
    address_line2?: string;
    city: string;
    name: string;
    state: string;
    zip_plus4?: string;
}
export enum AudienceType {
    CSV = "CSV",
    Map_ = "Map"
}
export enum CampaignStatus {
    InTransit = "InTransit",
    InProduction = "InProduction",
    Delivered = "Delivered",
    Created = "Created",
    SortedAtLocalHub = "SortedAtLocalHub"
}
export enum ProductType {
    SelfMailer = "SelfMailer",
    Booklet = "Booklet",
    Letter = "Letter",
    SnapPack = "SnapPack",
    Postcard = "Postcard"
}
export interface backendInterface {
    createCampaign(product: ProductSelection, recipientCount: bigint, audienceType: AudienceType): Promise<string>;
    exportCampaignRecipients(campaignId: string): Promise<string | null>;
    fireLobOutcall(campaignId: string, recipientId: string, lobKey: string): Promise<string>;
    getAdminKeys(): Promise<AdminKeys>;
    getCampaign(id: string): Promise<CampaignRecordShared | null>;
    getCampaigns(): Promise<Array<CampaignRecordShared>>;
    getCanvasState(campaignId: string): Promise<CanvasState | null>;
    getTrackingEvents(campaignId: string): Promise<Array<TrackingEvent>>;
    handleLobWebhook(payload: string): Promise<boolean>;
    saveAdminKeys(keys: AdminKeys): Promise<boolean>;
    saveCanvasState(campaignId: string, canvas: CanvasState): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCampaignStatus(id: string, status: CampaignStatus, lobEventId: string, timestamp: bigint): Promise<boolean>;
    verifyAddresses(addresses: Array<AddressInput>): Promise<Array<AddressVerificationResult>>;
}
import type { AddressInput as _AddressInput, AddressVerificationResult as _AddressVerificationResult, AdminKeys as _AdminKeys, AudienceType as _AudienceType, CampaignRecordShared as _CampaignRecordShared, CampaignStatus as _CampaignStatus, CanvasState as _CanvasState, LogoState as _LogoState, ProductSelection as _ProductSelection, ProductType as _ProductType, QrCodeState as _QrCodeState, TextBlockState as _TextBlockState, VerifiedAddress as _VerifiedAddress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCampaign(arg0: ProductSelection, arg1: bigint, arg2: AudienceType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCampaign(to_candid_ProductSelection_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_AudienceType_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCampaign(to_candid_ProductSelection_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_AudienceType_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async exportCampaignRecipients(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.exportCampaignRecipients(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportCampaignRecipients(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async fireLobOutcall(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fireLobOutcall(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fireLobOutcall(arg0, arg1, arg2);
            return result;
        }
    }
    async getAdminKeys(): Promise<AdminKeys> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminKeys();
                return from_candid_AdminKeys_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminKeys();
            return from_candid_AdminKeys_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampaign(arg0: string): Promise<CampaignRecordShared | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaign(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaign(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampaigns(): Promise<Array<CampaignRecordShared>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaigns();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaigns();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanvasState(arg0: string): Promise<CanvasState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanvasState(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanvasState(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrackingEvents(arg0: string): Promise<Array<TrackingEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrackingEvents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrackingEvents(arg0);
            return result;
        }
    }
    async handleLobWebhook(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.handleLobWebhook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleLobWebhook(arg0);
            return result;
        }
    }
    async saveAdminKeys(arg0: AdminKeys): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAdminKeys(to_candid_AdminKeys_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAdminKeys(to_candid_AdminKeys_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCanvasState(arg0: string, arg1: CanvasState): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCanvasState(arg0, to_candid_CanvasState_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCanvasState(arg0, to_candid_CanvasState_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCampaignStatus(arg0: string, arg1: CampaignStatus, arg2: string, arg3: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCampaignStatus(arg0, to_candid_CampaignStatus_n30(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCampaignStatus(arg0, to_candid_CampaignStatus_n30(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async verifyAddresses(arg0: Array<AddressInput>): Promise<Array<AddressVerificationResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAddresses(to_candid_vec_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAddresses(to_candid_vec_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AddressInput_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddressInput): AddressInput {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_AddressVerificationResult_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddressVerificationResult): AddressVerificationResult {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_AdminKeys_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminKeys): AdminKeys {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AudienceType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudienceType): AudienceType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_CampaignRecordShared_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignRecordShared): CampaignRecordShared {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_CampaignStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignStatus): CampaignStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_CanvasState_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CanvasState): CanvasState {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ProductSelection_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductSelection): ProductSelection {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ProductType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_VerifiedAddress_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifiedAddress): VerifiedAddress {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CampaignRecordShared]): CampaignRecordShared | null {
    return value.length === 0 ? null : from_candid_CampaignRecordShared_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CanvasState]): CanvasState | null {
    return value.length === 0 ? null : from_candid_CanvasState_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QrCodeState]): QrCodeState | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VerifiedAddress]): VerifiedAddress | null {
    return value.length === 0 ? null : from_candid_VerifiedAddress_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CampaignStatus;
    createdAt: bigint;
    trackingId: [] | [string];
    canvasState: [] | [_CanvasState];
    designTemplateId: [] | [string];
    recipientCount: bigint;
    audienceType: _AudienceType;
    product: _ProductSelection;
}): {
    id: string;
    status: CampaignStatus;
    createdAt: bigint;
    trackingId?: string;
    canvasState?: CanvasState;
    designTemplateId?: string;
    recipientCount: bigint;
    audienceType: AudienceType;
    product: ProductSelection;
} {
    return {
        id: value.id,
        status: from_candid_CampaignStatus_n13(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        trackingId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.trackingId)),
        canvasState: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.canvasState)),
        designTemplateId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.designTemplateId)),
        recipientCount: value.recipientCount,
        audienceType: from_candid_AudienceType_n19(_uploadFile, _downloadFile, value.audienceType),
        product: from_candid_ProductSelection_n21(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundImageUrl: [] | [string];
    logos: Array<_LogoState>;
    textBlocks: Array<_TextBlockState>;
    qrCode: [] | [_QrCodeState];
}): {
    backgroundImageUrl?: string;
    logos: Array<LogoState>;
    textBlocks: Array<TextBlockState>;
    qrCode?: QrCodeState;
} {
    return {
        backgroundImageUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.backgroundImageUrl)),
        logos: value.logos,
        textBlocks: value.textBlocks,
        qrCode: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.qrCode))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productType: _ProductType;
    layoutVariant: string;
    colorOption: [] | [string];
}): {
    productType: ProductType;
    layoutVariant: string;
    colorOption?: string;
} {
    return {
        productType: from_candid_ProductType_n23(_uploadFile, _downloadFile, value.productType),
        layoutVariant: value.layoutVariant,
        colorOption: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.colorOption))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: [] | [_VerifiedAddress];
    errorMessage: [] | [string];
    input: _AddressInput;
    isValid: boolean;
}): {
    verified?: VerifiedAddress;
    errorMessage?: string;
    input: AddressInput;
    isValid: boolean;
} {
    return {
        verified: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.verified)),
        errorMessage: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.errorMessage)),
        input: from_candid_AddressInput_n41(_uploadFile, _downloadFile, value.input),
        isValid: value.isValid
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    zip_code: string;
    address_line1: string;
    address_line2: [] | [string];
    city: string;
    name: string;
    state: string;
    zip_plus4: [] | [string];
}): {
    zip_code: string;
    address_line1: string;
    address_line2?: string;
    city: string;
    name: string;
    state: string;
    zip_plus4?: string;
} {
    return {
        zip_code: value.zip_code,
        address_line1: value.address_line1,
        address_line2: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.address_line2)),
        city: value.city,
        name: value.name,
        state: value.state,
        zip_plus4: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.zip_plus4))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    zip_code: string;
    address_line1: string;
    address_line2: [] | [string];
    city: string;
    name: string;
    state: string;
}): {
    zip_code: string;
    address_line1: string;
    address_line2?: string;
    city: string;
    name: string;
    state: string;
} {
    return {
        zip_code: value.zip_code,
        address_line1: value.address_line1,
        address_line2: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.address_line2)),
        city: value.city,
        name: value.name,
        state: value.state
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resendKey: [] | [string];
    lobKey: [] | [string];
    stripeKey: [] | [string];
}): {
    resendKey?: string;
    lobKey?: string;
    stripeKey?: string;
} {
    return {
        resendKey: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.resendKey)),
        lobKey: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.lobKey)),
        stripeKey: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.stripeKey))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InTransit: null;
} | {
    InProduction: null;
} | {
    Delivered: null;
} | {
    Created: null;
} | {
    SortedAtLocalHub: null;
}): CampaignStatus {
    return "InTransit" in value ? CampaignStatus.InTransit : "InProduction" in value ? CampaignStatus.InProduction : "Delivered" in value ? CampaignStatus.Delivered : "Created" in value ? CampaignStatus.Created : "SortedAtLocalHub" in value ? CampaignStatus.SortedAtLocalHub : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CSV: null;
} | {
    Map: null;
}): AudienceType {
    return "CSV" in value ? AudienceType.CSV : "Map" in value ? AudienceType.Map : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SelfMailer: null;
} | {
    Booklet: null;
} | {
    Letter: null;
} | {
    SnapPack: null;
} | {
    Postcard: null;
}): ProductType {
    return "SelfMailer" in value ? ProductType.SelfMailer : "Booklet" in value ? ProductType.Booklet : "Letter" in value ? ProductType.Letter : "SnapPack" in value ? ProductType.SnapPack : "Postcard" in value ? ProductType.Postcard : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CampaignRecordShared>): Array<CampaignRecordShared> {
    return value.map((x)=>from_candid_CampaignRecordShared_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AddressVerificationResult>): Array<AddressVerificationResult> {
    return value.map((x)=>from_candid_AddressVerificationResult_n36(_uploadFile, _downloadFile, x));
}
function to_candid_AddressInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddressInput): _AddressInput {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_AdminKeys_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminKeys): _AdminKeys {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_AudienceType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudienceType): _AudienceType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CampaignStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignStatus): _CampaignStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_CanvasState_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CanvasState): _CanvasState {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_ProductSelection_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductSelection): _ProductSelection {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ProductType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): _ProductType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productType: ProductType;
    layoutVariant: string;
    colorOption?: string;
}): {
    productType: _ProductType;
    layoutVariant: string;
    colorOption: [] | [string];
} {
    return {
        productType: to_candid_ProductType_n3(_uploadFile, _downloadFile, value.productType),
        layoutVariant: value.layoutVariant,
        colorOption: value.colorOption ? candid_some(value.colorOption) : candid_none()
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resendKey?: string;
    lobKey?: string;
    stripeKey?: string;
}): {
    resendKey: [] | [string];
    lobKey: [] | [string];
    stripeKey: [] | [string];
} {
    return {
        resendKey: value.resendKey ? candid_some(value.resendKey) : candid_none(),
        lobKey: value.lobKey ? candid_some(value.lobKey) : candid_none(),
        stripeKey: value.stripeKey ? candid_some(value.stripeKey) : candid_none()
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundImageUrl?: string;
    logos: Array<LogoState>;
    textBlocks: Array<TextBlockState>;
    qrCode?: QrCodeState;
}): {
    backgroundImageUrl: [] | [string];
    logos: Array<_LogoState>;
    textBlocks: Array<_TextBlockState>;
    qrCode: [] | [_QrCodeState];
} {
    return {
        backgroundImageUrl: value.backgroundImageUrl ? candid_some(value.backgroundImageUrl) : candid_none(),
        logos: value.logos,
        textBlocks: value.textBlocks,
        qrCode: value.qrCode ? candid_some(value.qrCode) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    zip_code: string;
    address_line1: string;
    address_line2?: string;
    city: string;
    name: string;
    state: string;
}): {
    zip_code: string;
    address_line1: string;
    address_line2: [] | [string];
    city: string;
    name: string;
    state: string;
} {
    return {
        zip_code: value.zip_code,
        address_line1: value.address_line1,
        address_line2: value.address_line2 ? candid_some(value.address_line2) : candid_none(),
        city: value.city,
        name: value.name,
        state: value.state
    };
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignStatus): {
    InTransit: null;
} | {
    InProduction: null;
} | {
    Delivered: null;
} | {
    Created: null;
} | {
    SortedAtLocalHub: null;
} {
    return value == CampaignStatus.InTransit ? {
        InTransit: null
    } : value == CampaignStatus.InProduction ? {
        InProduction: null
    } : value == CampaignStatus.Delivered ? {
        Delivered: null
    } : value == CampaignStatus.Created ? {
        Created: null
    } : value == CampaignStatus.SortedAtLocalHub ? {
        SortedAtLocalHub: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): {
    SelfMailer: null;
} | {
    Booklet: null;
} | {
    Letter: null;
} | {
    SnapPack: null;
} | {
    Postcard: null;
} {
    return value == ProductType.SelfMailer ? {
        SelfMailer: null
    } : value == ProductType.Booklet ? {
        Booklet: null
    } : value == ProductType.Letter ? {
        Letter: null
    } : value == ProductType.SnapPack ? {
        SnapPack: null
    } : value == ProductType.Postcard ? {
        Postcard: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudienceType): {
    CSV: null;
} | {
    Map: null;
} {
    return value == AudienceType.CSV ? {
        CSV: null
    } : value == AudienceType.Map ? {
        Map_: null
    } : value;
}
function to_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AddressInput>): Array<_AddressInput> {
    return value.map((x)=>to_candid_AddressInput_n33(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
