/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import { IDL } from "@icp-sdk/core/candid";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    body: Uint8Array;
    headers: Array<http_header>;
    status: bigint;
}
export interface http_header {
    name: string;
    value: string;
}
export interface WebhookResult {
    campaignId?: string;
    error?: string;
    ok: boolean;
    status?: CampaignStatus;
}
export interface VerifiedAddress {
    address_line1: string;
    address_line2?: string;
    city: string;
    name: string;
    state: string;
    zip_code: string;
    zip_plus4?: string;
}
export interface VerificationBatchResult {
    addressListId?: string;
    error?: string;
    invalidCount: bigint;
    ok: boolean;
    results: Array<AddressVerificationResult>;
    validCount: bigint;
}
export interface UserAccountShared {
    createdAt: bigint;
    creditBalance: bigint;
    email: string;
    firstPaymentAt?: bigint;
    freeMonthsAvailable: bigint;
    id: string;
    referralCode: string;
    referralCount: bigint;
    referralCreditsEarned: bigint;
    referralCreditsRedeemed: bigint;
    referralLink: string;
    referredBy?: string;
    subscriptionActive: boolean;
    subscriptionRenewsAt: bigint;
    updatedAt: bigint;
}
export interface TransformationOutput {
    body: Uint8Array;
    headers: Array<http_header>;
    status: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export enum TrackingSource {
    Manual = "Manual",
    Poll = "Poll",
    System = "System",
    Webhook = "Webhook"
}
export interface TrackingResolveResult {
    campaignId?: string;
    destinationUrl?: string;
    ok: boolean;
    recipientId?: string;
}
export interface TrackingEvent {
    campaignId: string;
    detail?: string;
    eventType: string;
    id: bigint;
    providerEventId: string;
    source: TrackingSource;
    status: CampaignStatus;
    timestamp: bigint;
}
export interface TextBlockState {
    align: string;
    color: string;
    fontFamily: string;
    fontSize: number;
    fontWeight: bigint;
    height: number;
    id: string;
    text: string;
    width: number;
    x: number;
    y: number;
    zIndex: bigint;
}
export interface SyncResult {
    error?: string;
    newEvents: bigint;
    ok: boolean;
    status?: CampaignStatus;
}
export interface ReturnAddress {
    address_line1: string;
    address_line2?: string;
    city: string;
    name: string;
    organization?: string;
    state: string;
    zip_code: string;
}
export interface ReferralStats {
    freeMonthsAvailable: bigint;
    referralCode: string;
    referralCount: bigint;
    referralCreditsEarned: bigint;
    referralCreditsRedeemed: bigint;
    referralLink: string;
    rewards: Array<ReferralReward>;
    subscriptionActive: boolean;
}
export interface ReferralReward {
    amountCents: bigint;
    id: bigint;
    paymentIntentId: string;
    refereeId: string;
    referrerId: string;
    timestamp: bigint;
}
export interface QrScanStats {
    recentScans: Array<QrScanEvent>;
    totalScans: bigint;
    uniqueRecipients: bigint;
}
export interface QrScanEvent {
    campaignId: string;
    recipientId: string;
    timestamp: bigint;
    userAgent?: string;
}
export enum QrMode {
    DynamicTracking = "DynamicTracking",
    StaticUrl = "StaticUrl"
}
export interface QrCodeState {
    background: string;
    caption?: string;
    foreground: string;
    id: string;
    mode: QrMode;
    size: number;
    url: string;
    x: number;
    y: number;
    zIndex: bigint;
}
export interface PublicConfig {
    click2mailConfigured: boolean;
    click2mailEnvironment: Click2MailEnvironment;
    openAiConfigured: boolean;
    referralBaseUrl: string;
    resendConfigured: boolean;
    sandboxCheckout: boolean;
    stripeConfigured: boolean;
    stripePublishableKey?: string;
    trackingBaseUrl: string;
}
export enum ProductionStatus {
    AddressListReady = "AddressListReady",
    AwaitingPayment = "AwaitingPayment",
    DocumentUploaded = "DocumentUploaded",
    Draft = "Draft",
    Failed = "Failed",
    JobCreated = "JobCreated",
    ReadyToDispatch = "ReadyToDispatch",
    Submitted = "Submitted"
}
export enum ProductType {
    Booklet = "Booklet",
    Brochure = "Brochure",
    CardStock = "CardStock",
    CertifiedMail = "CertifiedMail",
    Eddm = "Eddm",
    Flyer = "Flyer",
    Letter = "Letter",
    Notecard = "Notecard",
    Postcard = "Postcard",
    PriorityMail = "PriorityMail",
    PriorityMailExpress = "PriorityMailExpress",
    RackCard = "RackCard",
    ReplyMail = "ReplyMail",
    SelfMailer = "SelfMailer",
    SnapPack = "SnapPack"
}
export interface ProductSelection {
    colorOption?: string;
    layoutVariant: string;
    productType: ProductType;
}
export interface PrintSpec {
    color: string;
    documentClass: string;
    envelope?: string;
    layout: string;
    mailClass: MailClass;
    paperType: string;
    printOption: string;
    productionTime: string;
}
export interface PricingRow {
    baseCostCents: bigint;
    displayName: string;
    heightInches: number;
    layoutVariant: string;
    marginCents: bigint;
    marginPercent: bigint;
    printSpec: PrintSpec;
    productType: ProductType;
    retailPriceCents: bigint;
    widthInches: number;
}
export interface PresetResult {
    error?: string;
    ok: boolean;
    presetId?: string;
}
export enum PaymentStatus {
    Paid = "Paid",
    Pending = "Pending",
    Refunded = "Refunded",
    Unpaid = "Unpaid",
    Waived = "Waived"
}
export enum PaymentState {
    Created = "Created",
    Failed = "Failed",
    Succeeded = "Succeeded",
    Waived = "Waived"
}
export enum PaymentPurpose {
    CampaignOrder = "CampaignOrder",
    CreditPack = "CreditPack",
    Subscription = "Subscription"
}
export interface PaymentIntentResult {
    amountCents?: bigint;
    clientSecret?: string;
    error?: string;
    ok: boolean;
    paymentIntentId?: string;
    publishableKey?: string;
    sandbox: boolean;
    waived: boolean;
}
export enum MailClass {
    FirstClass = "FirstClass",
    MarketingMail = "MarketingMail",
    Priority = "Priority",
    PriorityExpress = "PriorityExpress"
}
export interface LogoState {
    height: number;
    id: string;
    url: string;
    width: number;
    x: number;
    y: number;
    zIndex: bigint;
}
export interface HttpResponse {
    body: Uint8Array;
    headers: Array<HeaderField>;
    status_code: number;
    upgrade?: boolean;
}
export interface HttpRequest {
    body: Uint8Array;
    headers: Array<HeaderField>;
    method: string;
    url: string;
}
export type HeaderField = [string, string];
export interface DocumentUploadStatus {
    campaignId: string;
    complete: boolean;
    fileName: string;
    mimeType: string;
    receivedChunks: bigint;
    totalBytes: bigint;
    totalChunks: bigint;
}
export interface DispatchResult {
    addressListId?: string;
    documentId?: string;
    error?: string;
    jobId?: string;
    ok: boolean;
    productionStatus?: ProductionStatus;
}
export interface CreditResult {
    balance?: bigint;
    error?: string;
    ok: boolean;
}
export interface CreditPackInfo {
    bonusCredits: bigint;
    credits: bigint;
    name: string;
    pack: CreditPack;
    priceCents: bigint;
}
export enum CreditPack {
    Agency = "Agency",
    Growth = "Growth",
    Starter = "Starter"
}
export interface CreditLedgerEntry {
    balanceAfter: bigint;
    delta: bigint;
    id: bigint;
    reason: string;
    reference?: string;
    timestamp: bigint;
    userId: string;
}
export interface CreateCampaignResult {
    campaignId?: string;
    error?: string;
    ok: boolean;
    totalCents?: bigint;
    unitPriceCents?: bigint;
}
export interface CreateCampaignInput {
    audienceType: AudienceType;
    canvasState?: CanvasState;
    designTemplateId?: string;
    name: string;
    product: ProductSelection;
    qrDestinationUrl?: string;
    recipientCount: bigint;
    recipients: Array<VerifiedAddress>;
    returnAddress?: ReturnAddress;
    sourcePresetId?: string;
}
export interface ConfirmPaymentResult {
    campaignId?: string;
    creditBalance?: bigint;
    error?: string;
    ok: boolean;
    referralRewardApplied: boolean;
    state?: PaymentState;
    subscriptionActive?: boolean;
}
export enum Click2MailEnvironment {
    Production = "Production",
    Staging = "Staging"
}
export interface CanvasState {
    back: CanvasSide;
    designPpi: bigint;
    front: CanvasSide;
    heightInches: number;
    widthInches: number;
}
export interface CanvasSide {
    backgroundColor: string;
    backgroundImageUrl?: string;
    logos: Array<LogoState>;
    qrCodes: Array<QrCodeState>;
    textBlocks: Array<TextBlockState>;
}
export enum CampaignStatus {
    Created = "Created",
    Delivered = "Delivered",
    InProduction = "InProduction",
    InTransit = "InTransit",
    SortedAtLocalHub = "SortedAtLocalHub"
}
export interface CampaignRecordShared {
    audienceType: AudienceType;
    baseCostCents: bigint;
    c2mAddressListId?: string;
    c2mDocumentId?: string;
    c2mJobId?: string;
    canvasState?: CanvasState;
    createdAt: bigint;
    designTemplateId?: string;
    id: string;
    lastError?: string;
    name: string;
    ownerId: string;
    paymentIntentId?: string;
    paymentStatus: PaymentStatus;
    printSpec: PrintSpec;
    product: ProductSelection;
    productionStatus: ProductionStatus;
    qrDestinationUrl?: string;
    qrScanCount: bigint;
    recipientCount: bigint;
    returnAddress?: ReturnAddress;
    sourcePresetId?: string;
    status: CampaignStatus;
    totalAmountChargedCents: bigint;
    unitPriceCents: bigint;
    updatedAt: bigint;
}
export enum AudienceType {
    CsvUpload = "CsvUpload",
    GeoRadius = "GeoRadius",
    SavedPreset = "SavedPreset"
}
export interface AudiencePresetShared {
    createdAt: bigint;
    id: string;
    name: string;
    ownerId: string;
    recipientCount: bigint;
    sourceCampaignId?: string;
    updatedAt: bigint;
}
export interface ApiResult {
    error?: string;
    ok: boolean;
}
export interface AiPricing {
    copyCredits: bigint;
    creditValueCents: bigint;
    hdImageCredits: bigint;
    monthlyAllowance: bigint;
    packs: Array<CreditPackInfo>;
    squareImageCredits: bigint;
    wideImageCredits: bigint;
}
export enum AiImageSize {
    Square1024 = "Square1024",
    Wide1792 = "Wide1792",
    WideHd1792 = "WideHd1792"
}
export interface AiImageResult {
    creditBalance?: bigint;
    creditsCharged: bigint;
    error?: string;
    imageUrl?: string;
    ok: boolean;
    revisedPrompt?: string;
}
export interface AiCopyResult {
    bullets: Array<string>;
    creditBalance?: bigint;
    creditsCharged: bigint;
    ctas: Array<string>;
    error?: string;
    headlines: Array<string>;
    ok: boolean;
}
export interface AiCopyInput {
    businessName: string;
    callToAction: string;
    industry: string;
    offer: string;
    tone?: string;
}
export interface AdminKeysView {
    adminPrincipal?: string;
    callerIsAdmin: boolean;
    click2mailEnvironment: Click2MailEnvironment;
    click2mailPasswordMasked?: string;
    click2mailUsername?: string;
    openAiKeyMasked?: string;
    outcallProxyUrl?: string;
    resendKeyMasked?: string;
    sandboxCheckout: boolean;
    stripePublishableKey?: string;
    stripeSecretKeyMasked?: string;
    webhookPath: string;
    webhookSecretMasked?: string;
}
export interface AdminKeysInput {
    click2mailEnvironment?: Click2MailEnvironment;
    click2mailPassword?: string;
    click2mailUsername?: string;
    openAiKey?: string;
    outcallProxyUrl?: string;
    resendKey?: string;
    sandboxCheckout?: boolean;
    stripePublishableKey?: string;
    stripeSecretKey?: string;
    webhookSecret?: string;
}
export interface AddressVerificationResult {
    errorMessage?: string;
    input: AddressInput;
    isValid: boolean;
    verified?: VerifiedAddress;
}
export interface AddressInput {
    address_line1: string;
    address_line2?: string;
    city: string;
    name: string;
    state: string;
    zip_code: string;
}
export interface AccountResult {
    account?: UserAccountShared;
    error?: string;
    ok: boolean;
}
export interface backendInterface {
    applyReferralReward(arg0: string): Promise<ApiResult>;
    confirmPayment(arg0: string): Promise<ConfirmPaymentResult>;
    createCampaign(arg0: CreateCampaignInput): Promise<CreateCampaignResult>;
    createPaymentIntent(arg0: PaymentPurpose, arg1: string | null, arg2: CreditPack | null): Promise<PaymentIntentResult>;
    deductAiCredits(arg0: bigint, arg1: string): Promise<CreditResult>;
    deletePreset(arg0: string): Promise<ApiResult>;
    dispatchClick2MailJob(arg0: string): Promise<DispatchResult>;
    ensureAccount(arg0: string | null, arg1: string | null): Promise<AccountResult>;
    executeClick2MailVerification(arg0: Array<AddressInput>): Promise<VerificationBatchResult>;
    exportCampaignRecipients(arg0: string): Promise<string | null>;
    generateAiCopy(arg0: AiCopyInput): Promise<AiCopyResult>;
    generateAiImage(arg0: string, arg1: AiImageSize): Promise<AiImageResult>;
    getAdminKeys(): Promise<AdminKeysView>;
    getAiPricing(): Promise<AiPricing>;
    getCampaign(arg0: string): Promise<CampaignRecordShared | null>;
    getCampaignRecipients(arg0: string): Promise<Array<VerifiedAddress>>;
    getCampaigns(): Promise<Array<CampaignRecordShared>>;
    getCanvasState(arg0: string): Promise<CanvasState | null>;
    getCreditLedger(): Promise<Array<CreditLedgerEntry>>;
    getDocumentUploadStatus(arg0: string): Promise<DocumentUploadStatus | null>;
    getMyAccount(): Promise<UserAccountShared | null>;
    getPresetAddresses(arg0: string): Promise<Array<VerifiedAddress>>;
    getPricingLedger(): Promise<Array<PricingRow>>;
    getPublicConfig(): Promise<PublicConfig>;
    getQrScanStats(arg0: string): Promise<QrScanStats>;
    getReferralStats(): Promise<ReferralStats | null>;
    getTrackingEvents(arg0: string): Promise<Array<TrackingEvent>>;
    handleDeliveryWebhook(arg0: string, arg1: string): Promise<WebhookResult>;
    http_request(arg0: HttpRequest): Promise<HttpResponse>;
    http_request_update(arg0: HttpRequest): Promise<HttpResponse>;
    listPresets(): Promise<Array<AudiencePresetShared>>;
    pollActiveTracking(): Promise<bigint>;
    resolveTrackingLink(arg0: string, arg1: string | null): Promise<TrackingResolveResult>;
    saveAdminKeys(arg0: AdminKeysInput): Promise<ApiResult>;
    saveCanvasState(arg0: string, arg1: CanvasState): Promise<boolean>;
    savePreset(arg0: string, arg1: Array<VerifiedAddress>, arg2: string | null): Promise<PresetResult>;
    syncClick2MailTracking(arg0: string): Promise<SyncResult>;
    transform(arg0: TransformationInput): Promise<TransformationOutput>;
    updateAccountEmail(arg0: string): Promise<ApiResult>;
    updateCampaignStatus(arg0: string, arg1: CampaignStatus, arg2: string, arg3: bigint): Promise<boolean>;
    updatePreset(arg0: string, arg1: string, arg2: Array<VerifiedAddress>): Promise<ApiResult>;
    uploadDocumentChunk(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: Uint8Array): Promise<ApiResult>;
}
// ─── Type-directed candid <-> TS conversion (opt <-> undefined/null, variant <-> enum string) ───
function isNullType(t: IDL.Type): boolean {
    return t instanceof IDL.NullClass;
}
function resolve(t: IDL.Type): IDL.Type {
    return t instanceof IDL.RecClass ? (t.getType() as IDL.Type) : t;
}
function toCandid(t0: IDL.Type, v: any): any {
    const t = resolve(t0);
    if (t instanceof IDL.OptClass) {
        return v === undefined || v === null ? [] : [toCandid(t._type, v)];
    }
    if (t instanceof IDL.VecClass) {
        if (t._type instanceof IDL.FixedNatClass && (t._type as any)._bits === 8) {
            return v instanceof Uint8Array ? v : Uint8Array.from(v ?? []);
        }
        return (v ?? []).map((x: any) => toCandid(t._type, x));
    }
    if (t instanceof IDL.TupleClass) {
        const comps = (t as any)._components as IDL.Type[];
        return comps.map((ct, i) => toCandid(ct, v[i]));
    }
    if (t instanceof IDL.RecordClass) {
        const out: Record<string, any> = {};
        for (const [name, ft] of t._fields) {
            out[name] = toCandid(ft, v?.[name]);
        }
        return out;
    }
    if (t instanceof IDL.VariantClass) {
        if (typeof v === "string") {
            return { [v]: null };
        }
        const key = Object.keys(v)[0];
        const ft = t._fields.find(([n]) => n === key)?.[1];
        return { [key]: ft ? toCandid(ft, v[key]) : null };
    }
    return v;
}
function fromCandid(t0: IDL.Type, v: any, topLevel: boolean): any {
    const t = resolve(t0);
    if (t instanceof IDL.OptClass) {
        if (!Array.isArray(v) || v.length === 0) {
            return topLevel ? null : undefined;
        }
        return fromCandid(t._type, v[0], false);
    }
    if (t instanceof IDL.VecClass) {
        if (v instanceof Uint8Array) {
            return v;
        }
        return (v ?? []).map((x: any) => fromCandid(t._type, x, false));
    }
    if (t instanceof IDL.TupleClass) {
        const comps = (t as any)._components as IDL.Type[];
        return comps.map((ct, i) => fromCandid(ct, v[i], false));
    }
    if (t instanceof IDL.RecordClass) {
        const out: Record<string, any> = {};
        for (const [name, ft] of t._fields) {
            const converted = fromCandid(ft, v?.[name], false);
            if (converted !== undefined) {
                out[name] = converted;
            }
        }
        return out;
    }
    if (t instanceof IDL.VariantClass) {
        const key = Object.keys(v ?? {})[0];
        const ft = t._fields.find(([n]) => n === key)?.[1];
        if (!ft || isNullType(ft)) {
            return key;
        }
        return { [key]: fromCandid(ft, v[key], false) };
    }
    return v;
}
const _service = idlFactory({ IDL }) as IDL.ServiceClass;
const _methods = new Map<string, IDL.FuncClass>(_service._fields as Array<[string, IDL.FuncClass]>);
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    private async _call(name: string, args: any[]): Promise<any> {
        const fn = _methods.get(name);
        if (!fn) {
            throw new Error(`Unknown backend method: ${name}`);
        }
        const candidArgs = fn.argTypes.map((t, i) => toCandid(t, args[i]));
        try {
            const result = await (this.actor as any)[name](...candidArgs);
            if (fn.retTypes.length === 0) {
                return undefined;
            }
            if (fn.retTypes.length === 1) {
                return fromCandid(fn.retTypes[0], result, true);
            }
            return fn.retTypes.map((t, i) => fromCandid(t, result[i], true));
        } catch (e) {
            if (this.processError) {
                this.processError(e);
                throw new Error("unreachable");
            }
            throw e;
        }
    }
    async applyReferralReward(arg0: string): Promise<ApiResult> {
        return this._call("applyReferralReward", [arg0]) as Promise<ApiResult>;
    }
    async confirmPayment(arg0: string): Promise<ConfirmPaymentResult> {
        return this._call("confirmPayment", [arg0]) as Promise<ConfirmPaymentResult>;
    }
    async createCampaign(arg0: CreateCampaignInput): Promise<CreateCampaignResult> {
        return this._call("createCampaign", [arg0]) as Promise<CreateCampaignResult>;
    }
    async createPaymentIntent(arg0: PaymentPurpose, arg1: string | null, arg2: CreditPack | null): Promise<PaymentIntentResult> {
        return this._call("createPaymentIntent", [arg0, arg1, arg2]) as Promise<PaymentIntentResult>;
    }
    async deductAiCredits(arg0: bigint, arg1: string): Promise<CreditResult> {
        return this._call("deductAiCredits", [arg0, arg1]) as Promise<CreditResult>;
    }
    async deletePreset(arg0: string): Promise<ApiResult> {
        return this._call("deletePreset", [arg0]) as Promise<ApiResult>;
    }
    async dispatchClick2MailJob(arg0: string): Promise<DispatchResult> {
        return this._call("dispatchClick2MailJob", [arg0]) as Promise<DispatchResult>;
    }
    async ensureAccount(arg0: string | null, arg1: string | null): Promise<AccountResult> {
        return this._call("ensureAccount", [arg0, arg1]) as Promise<AccountResult>;
    }
    async executeClick2MailVerification(arg0: Array<AddressInput>): Promise<VerificationBatchResult> {
        return this._call("executeClick2MailVerification", [arg0]) as Promise<VerificationBatchResult>;
    }
    async exportCampaignRecipients(arg0: string): Promise<string | null> {
        return this._call("exportCampaignRecipients", [arg0]) as Promise<string | null>;
    }
    async generateAiCopy(arg0: AiCopyInput): Promise<AiCopyResult> {
        return this._call("generateAiCopy", [arg0]) as Promise<AiCopyResult>;
    }
    async generateAiImage(arg0: string, arg1: AiImageSize): Promise<AiImageResult> {
        return this._call("generateAiImage", [arg0, arg1]) as Promise<AiImageResult>;
    }
    async getAdminKeys(): Promise<AdminKeysView> {
        return this._call("getAdminKeys", []) as Promise<AdminKeysView>;
    }
    async getAiPricing(): Promise<AiPricing> {
        return this._call("getAiPricing", []) as Promise<AiPricing>;
    }
    async getCampaign(arg0: string): Promise<CampaignRecordShared | null> {
        return this._call("getCampaign", [arg0]) as Promise<CampaignRecordShared | null>;
    }
    async getCampaignRecipients(arg0: string): Promise<Array<VerifiedAddress>> {
        return this._call("getCampaignRecipients", [arg0]) as Promise<Array<VerifiedAddress>>;
    }
    async getCampaigns(): Promise<Array<CampaignRecordShared>> {
        return this._call("getCampaigns", []) as Promise<Array<CampaignRecordShared>>;
    }
    async getCanvasState(arg0: string): Promise<CanvasState | null> {
        return this._call("getCanvasState", [arg0]) as Promise<CanvasState | null>;
    }
    async getCreditLedger(): Promise<Array<CreditLedgerEntry>> {
        return this._call("getCreditLedger", []) as Promise<Array<CreditLedgerEntry>>;
    }
    async getDocumentUploadStatus(arg0: string): Promise<DocumentUploadStatus | null> {
        return this._call("getDocumentUploadStatus", [arg0]) as Promise<DocumentUploadStatus | null>;
    }
    async getMyAccount(): Promise<UserAccountShared | null> {
        return this._call("getMyAccount", []) as Promise<UserAccountShared | null>;
    }
    async getPresetAddresses(arg0: string): Promise<Array<VerifiedAddress>> {
        return this._call("getPresetAddresses", [arg0]) as Promise<Array<VerifiedAddress>>;
    }
    async getPricingLedger(): Promise<Array<PricingRow>> {
        return this._call("getPricingLedger", []) as Promise<Array<PricingRow>>;
    }
    async getPublicConfig(): Promise<PublicConfig> {
        return this._call("getPublicConfig", []) as Promise<PublicConfig>;
    }
    async getQrScanStats(arg0: string): Promise<QrScanStats> {
        return this._call("getQrScanStats", [arg0]) as Promise<QrScanStats>;
    }
    async getReferralStats(): Promise<ReferralStats | null> {
        return this._call("getReferralStats", []) as Promise<ReferralStats | null>;
    }
    async getTrackingEvents(arg0: string): Promise<Array<TrackingEvent>> {
        return this._call("getTrackingEvents", [arg0]) as Promise<Array<TrackingEvent>>;
    }
    async handleDeliveryWebhook(arg0: string, arg1: string): Promise<WebhookResult> {
        return this._call("handleDeliveryWebhook", [arg0, arg1]) as Promise<WebhookResult>;
    }
    async http_request(arg0: HttpRequest): Promise<HttpResponse> {
        return this._call("http_request", [arg0]) as Promise<HttpResponse>;
    }
    async http_request_update(arg0: HttpRequest): Promise<HttpResponse> {
        return this._call("http_request_update", [arg0]) as Promise<HttpResponse>;
    }
    async listPresets(): Promise<Array<AudiencePresetShared>> {
        return this._call("listPresets", []) as Promise<Array<AudiencePresetShared>>;
    }
    async pollActiveTracking(): Promise<bigint> {
        return this._call("pollActiveTracking", []) as Promise<bigint>;
    }
    async resolveTrackingLink(arg0: string, arg1: string | null): Promise<TrackingResolveResult> {
        return this._call("resolveTrackingLink", [arg0, arg1]) as Promise<TrackingResolveResult>;
    }
    async saveAdminKeys(arg0: AdminKeysInput): Promise<ApiResult> {
        return this._call("saveAdminKeys", [arg0]) as Promise<ApiResult>;
    }
    async saveCanvasState(arg0: string, arg1: CanvasState): Promise<boolean> {
        return this._call("saveCanvasState", [arg0, arg1]) as Promise<boolean>;
    }
    async savePreset(arg0: string, arg1: Array<VerifiedAddress>, arg2: string | null): Promise<PresetResult> {
        return this._call("savePreset", [arg0, arg1, arg2]) as Promise<PresetResult>;
    }
    async syncClick2MailTracking(arg0: string): Promise<SyncResult> {
        return this._call("syncClick2MailTracking", [arg0]) as Promise<SyncResult>;
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        return this._call("transform", [arg0]) as Promise<TransformationOutput>;
    }
    async updateAccountEmail(arg0: string): Promise<ApiResult> {
        return this._call("updateAccountEmail", [arg0]) as Promise<ApiResult>;
    }
    async updateCampaignStatus(arg0: string, arg1: CampaignStatus, arg2: string, arg3: bigint): Promise<boolean> {
        return this._call("updateCampaignStatus", [arg0, arg1, arg2, arg3]) as Promise<boolean>;
    }
    async updatePreset(arg0: string, arg1: string, arg2: Array<VerifiedAddress>): Promise<ApiResult> {
        return this._call("updatePreset", [arg0, arg1, arg2]) as Promise<ApiResult>;
    }
    async uploadDocumentChunk(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: Uint8Array): Promise<ApiResult> {
        return this._call("uploadDocumentChunk", [arg0, arg1, arg2, arg3, arg4, arg5]) as Promise<ApiResult>;
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
